import "./globals.css"
import type { Metadata } from "next"
import localFont from "next/font/local"

const gtWalsheim = localFont({
  variable: "--gt-walsheim-pro",
  src: [
    {
      path: "../gt-walsheim-pro/GTWalsheimPro-Light.woff2",
      weight: "300",
      style: "normal"
    },
    {
      path: "../gt-walsheim-pro/GTWalsheimPro-Regular.woff2",
      weight: "400",
      style: "normal"
    },
    {
      path: "../gt-walsheim-pro/GTWalsheimPro-Bold.woff2",
      weight: "700",
      style: "normal"
    }
  ]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={gtWalsheim.className}>{children}</body>
    </html>
  )
}
